"python.analysis.diagnosticSeverityOverrides": {
        "reportArgumentType": "none",
        "reportAttributeAccessIssue": "none",
        "reportOptionalMemberAccess": "none",
        "reportCallIssue": "none",
        "reportUnusedImport": "none",  
        "reportUnknownParameterType": "none",  
        "reportUnknownMemberType": "none",  
        "reportGeneralTypeIssues": "none",
        "reportDeprecated": "none",
        "reportUnknownVariableType": "none", 
        "reportUnknownArgumentType": "none",
        "reportMissingTypeArgument": "none",
    },
